### ISSUE TITLE
Compile error with Angular 11

### ISSUE THREAD

**Issue by LucaMurarolli** [Passiverecords/angular-flag-icon-css#17]
Hi, 
there's a compiling error with Angular 11 due to private variable access.

![image](https://user-images.githubusercontent.com/57721117/107642902-c2cb2a00-6c75-11eb-8b8f-228d878927e0.png)

Squared and Country, used like attributes, are private in the component and so compiling with Ivy is possibile only by setting strictInputAccessModifiers to false in tsconfig.json:

  `"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": true,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": false,
    "strictTemplates": true
  }`

Is it possible to make squared and country public? Or to implement getters?

Thanks,
Best regards

**Comment by alexandr-efimov** [comment]
+1

**Comment by AnthonyLenglet** [comment]
Hi !
This package is now deprecated, please see #39 for more info and easier/less bloated alternative
