### ISSUE TITLE
am I missing a configuration?

### ISSUE THREAD

**Issue by chr1soscl** [Passiverecords/angular-flag-icon-css#2]
I installed the packages:
npm install ngx-flag-icon-css flag-icon-css

then I am using the tag in the html:
<flag-icon country="fr" squared></flag-icon>

but I am getting the below error:
1. If 'flag-icon' is an Angular component, then verify that it is part of this module.
2. If 'flag-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
<h2>Here are some links to help you start: </h2>

[ERROR ->]<flag-icon country="fr" squared></flag-icon>

**Comment by AnthonyLenglet** [comment]
You might've forgotten to declare the component in app.module.ts

**Comment by nelson6e65** [comment]
> You might've forgotten to declare the component in app.module.ts

This is not specified in the documentation. 

If someone, for A7:

```js
// . . .
import { NgxFlagIconCssModule } from 'ngx-flag-icon-css';

@NgModule({
  declarations: [
  ],
  imports: [
    // . . .
    NgxFlagIconCssModule
  ]
})
export class ComponentsModule { }
```

**Comment by gentunian** [comment]
@AnthonyLenglet can you please add the required things into docs? I cannot get it working either for Angular9.
