### ISSUE TITLE
Angular 13 - Ivy by default

### ISSUE THREAD

**Issue by AmitMY** [Passiverecords/angular-flag-icon-css#30]
Angular 13 build says:

> ⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
> 
> - ngx-flag-icon-css [es2015/esm2015] (https://github.com/Passiverecords/angular-flag-icon-css.git)
> 
> Encourage the library authors to publish an Ivy distribution.

Could you please publish an ivy dist?

**Comment by AnthonyLenglet** [comment]
Hi !
This package is now deprecated, please see #39 for more info
